using UnityEditor;
using UnityEngine;
using UnityEngine.Localization;
using UnityEditor.Localization;
using System.IO;
using System.Text;
using System.Linq;
using System;
using System.Reflection;

namespace LightHouse.Core.CustomEditors
{
    public class LocalizationWindow : EditorWindow
    {
        private LocalizationTableCollection selectedTable;
        private Type selectedAssetType = typeof(Sprite);
        private string[] assetTypeOptions = new string[] { "Sprite", "AudioClip", "GameObject", "TextAsset" };
        private int selectedAssetTypeIndex = 0;

        public string CustomAssetPath = "Assets/Localization/AutoGenerated";

        [MenuItem("Tools/Localization Window")]
        public static void ShowWindow()
        {
            GetWindow<LocalizationWindow>("Localization Window");
        }

        void OnGUI()
        {
            GUILayout.Label("Générer un ScriptableObject de Localized Entries", EditorStyles.boldLabel);

            selectedTable = (LocalizationTableCollection)EditorGUILayout.ObjectField("Table (String ou Asset)", selectedTable, typeof(LocalizationTableCollection), false);

            CustomAssetPath = EditorGUILayout.TextField("Chemin du dossier", CustomAssetPath);

            if (selectedTable is AssetTableCollection)
            {
                GUILayout.Label("Type d'asset (pour LocalizedAsset<T>)");
                selectedAssetTypeIndex = EditorGUILayout.Popup(selectedAssetTypeIndex, assetTypeOptions);
                selectedAssetType = Type.GetType("UnityEngine." + assetTypeOptions[selectedAssetTypeIndex] + ", UnityEngine");
            }

            if (selectedTable != null && GUILayout.Button("Générer le ScriptableObject"))
            {
                GenerateScript(selectedTable);
            }
        }

        void GenerateScript(LocalizationTableCollection table)
        {
            string prefix = table is StringTableCollection ? "LocalizedStringDatabase" : "LocalizedAssetDatabase";
            string className = $"{prefix}_{table.name}";
            string fileName = $"{className}.cs";

            // Recherche si le script existe déjà quelque part
            string existingScriptPath = AssetDatabase.FindAssets($"{className} t:Script")
                .Select(AssetDatabase.GUIDToAssetPath)
                .FirstOrDefault(path => Path.GetFileNameWithoutExtension(path) == className);

            string targetFolderPath;
            string fullScriptPath;

            if (!string.IsNullOrEmpty(existingScriptPath))
            {
                bool shouldReplace = EditorUtility.DisplayDialog(
                    "Script déjà existant",
                    $"Un script nommé \"{className}\" existe déjà à cet emplacement :\n{existingScriptPath}\n\nVeux-tu le remplacer ?",
                    "Remplacer",
                    "Annuler"
                );

                if (!shouldReplace)
                {
                    Debug.Log("❌ Génération annulée par l’utilisateur.");
                    return;
                }

                // ⚠️ On écrase dans le dossier existant
                targetFolderPath = Path.GetDirectoryName(existingScriptPath);
                fullScriptPath = existingScriptPath;
            }
            else
            {
                // Utilisation du dossier custom
                targetFolderPath = CustomAssetPath;
                fullScriptPath = Path.Combine(targetFolderPath, fileName);

                if (!Directory.Exists(targetFolderPath))
                    Directory.CreateDirectory(targetFolderPath);
            }

            // ✅ Génération du script
            var sharedEntries = table.SharedData.Entries;

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// Auto-generated ScriptableObject for localization keys");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Localization;");
            sb.AppendLine("using UnityEngine.Localization.Components;");
            sb.AppendLine();

            sb.AppendLine("namespace LightHouse.Localization");
            sb.AppendLine("{");
            sb.AppendLine($"\t[CreateAssetMenu(menuName = \"Localization/{className}\")]");
            sb.AppendLine($"\tpublic class {className} : ScriptableObject");
            sb.AppendLine("\t{");

            foreach (var entry in sharedEntries)
            {
                string sanitized = SanitizeKey(entry.Key);
                if (table is StringTableCollection)
                    sb.AppendLine($"\t\tpublic LocalizedString {sanitized};");
                else
                    sb.AppendLine($"\t\tpublic LocalizedAsset<{selectedAssetType.Name}> {sanitized};");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            File.WriteAllText(fullScriptPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"✅ Script généré : {fullScriptPath}");

            // Générer ou mettre à jour le ScriptableObject
            EditorApplication.delayCall += () =>
            {
                CreateAndPopulateSO(className, table, targetFolderPath);
            };
        }

        void CreateAndPopulateSO(string className, LocalizationTableCollection table, string folderPath)
        {
            var type = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a => a.GetTypes())
                .FirstOrDefault(t => t.Name == className);

            if (type == null)
            {
                Debug.LogError($"❌ Type {className} introuvable après compilation.");
                return;
            }

            string assetPath = Path.Combine(folderPath, $"{className}.asset");
            ScriptableObject asset = AssetDatabase.LoadAssetAtPath(assetPath, type) as ScriptableObject;

            if (asset != null)
            {
                bool shouldReplaceAsset = EditorUtility.DisplayDialog(
                    "Asset déjà existant",
                    $"Un ScriptableObject nommé \"{className}.asset\" existe déjà à cet emplacement :\n{assetPath}\n\nVeux-tu le mettre à jour ?",
                    "Mettre à jour",
                    "Annuler"
                );

                if (!shouldReplaceAsset)
                {
                    Debug.Log("❌ Mise à jour du ScriptableObject annulée par l’utilisateur.");
                    return;
                }

                Debug.Log($"⚠️ Asset existant mis à jour : {assetPath}");
            }
            else
            {
                asset = ScriptableObject.CreateInstance(type);
                AssetDatabase.CreateAsset(asset, assetPath);
                Debug.Log($"✅ Asset créé : {assetPath}");
            }

            foreach (var entry in table.SharedData.Entries)
            {
                string key = entry.Key;
                string fieldName = SanitizeKey(key);
                var field = type.GetField(fieldName, BindingFlags.Public | BindingFlags.Instance);
                if (field == null) continue;

                if (table is StringTableCollection && field.FieldType == typeof(LocalizedString))
                {
                    var locString = field.GetValue(asset) as LocalizedString;
                    if (locString == null)
                    {
                        locString = new LocalizedString();
                        field.SetValue(asset, locString);
                    }

                    locString.TableReference = table.TableCollectionNameReference;
                    locString.TableEntryReference = key;
                }
                else if (table is AssetTableCollection && field.FieldType.IsGenericType &&
                         field.FieldType.GetGenericTypeDefinition() == typeof(LocalizedAsset<>))
                {
                    var localizedAsset = field.GetValue(asset) as LocalizedAssetBase;
                    if (localizedAsset == null)
                    {
                        localizedAsset = Activator.CreateInstance(field.FieldType) as LocalizedAssetBase;
                        field.SetValue(asset, localizedAsset);
                    }

                    localizedAsset.TableReference = table.TableCollectionNameReference;
                    localizedAsset.TableEntryReference = key;
                }
            }

            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }


        string SanitizeKey(string key)
        {
            var sb = new StringBuilder();
            foreach (char c in key)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }
    }
}
