using UnityEditor;
using UnityEngine;
using UnityEngine.Localization;
using UnityEditor.Localization;
using System.IO;
using System.Text;
using System.Linq;
using System;
using System.Reflection;

namespace LightHouse.Core.CustomEditors
{
    public class LocalizationWindow : EditorWindow
    {
        private LocalizationTableCollection selectedTable;
        private Type selectedAssetType = typeof(Sprite);
        private string[] assetTypeOptions = new string[] { "Sprite", "AudioClip", "GameObject", "TextAsset" };
        private int selectedAssetTypeIndex = 0;

        private bool generateArray = false;

        public string CustomAssetPath = "Assets/Localization/AutoGenerated";

        private string _pendingClassName;
        private LocalizationTableCollection _pendingTable;
        private string _pendingFolderPath;

        private bool _shouldCreateSO = false;

        [MenuItem("Tools/Localization Window")]
        public static void ShowWindow()
        {
            GetWindow<LocalizationWindow>("Localization Window");
        }

        void OnGUI()
        {
            GUILayout.Label("Générer un ScriptableObject de Localized Entries", EditorStyles.boldLabel);

            selectedTable = (LocalizationTableCollection)EditorGUILayout.ObjectField(
                "Table (String ou Asset)",
                selectedTable,
                typeof(LocalizationTableCollection),
                false
            );

            CustomAssetPath = EditorGUILayout.TextField("Chemin du dossier", CustomAssetPath);
            generateArray = EditorGUILayout.Toggle("Générer un tableau global", generateArray);

            if (selectedTable is AssetTableCollection)
            {
                GUILayout.Label("Type d'asset (pour LocalizedAsset<T>)");
                selectedAssetTypeIndex = EditorGUILayout.Popup(selectedAssetTypeIndex, assetTypeOptions);
                selectedAssetType = Type.GetType("UnityEngine." + assetTypeOptions[selectedAssetTypeIndex] + ", UnityEngine");
            }

            if (selectedTable != null && GUILayout.Button("Générer le ScriptableObject"))
            {
                GenerateScript(selectedTable);
            }

            // 🔥 Poll propre (remplace tous les events Unity)
            TryCreateAssetIfReady();
        }

        void GenerateScript(LocalizationTableCollection table)
        {
            string prefix = table is StringTableCollection ? "LocalizedStringDatabase" : "LocalizedAssetDatabase";
            string className = $"{prefix}_{table.name}";
            string fileName = $"{className}.cs";

            string targetFolderPath = CustomAssetPath;
            string fullScriptPath = Path.Combine(targetFolderPath, fileName);

            if (!Directory.Exists(targetFolderPath))
                Directory.CreateDirectory(targetFolderPath);

            var sharedEntries = table.SharedData.Entries;

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// Auto-generated ScriptableObject for localization keys");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Localization;");
            sb.AppendLine();

            sb.AppendLine("namespace LightHouse.Localization");
            sb.AppendLine("{");
            sb.AppendLine($"\t[CreateAssetMenu(menuName = \"Localization/{className}\")]");
            sb.AppendLine($"\tpublic class {className} : ScriptableObject");
            sb.AppendLine("\t{");

            foreach (var entry in sharedEntries)
            {
                string sanitized = SanitizeKey(entry.Key);

                if (table is StringTableCollection)
                    sb.AppendLine($"\t\tpublic LocalizedString {sanitized};");
                else
                    sb.AppendLine($"\t\tpublic LocalizedAsset<{selectedAssetType.Name}> {sanitized};");
            }

            if (generateArray)
            {
                if (table is StringTableCollection)
                    sb.AppendLine("\t\tpublic LocalizedString[] All;");
                else
                    sb.AppendLine($"\t\tpublic LocalizedAsset<{selectedAssetType.Name}>[] All;");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            File.WriteAllText(fullScriptPath, sb.ToString());

            _pendingClassName = className;
            _pendingTable = table;
            _pendingFolderPath = targetFolderPath;

            _shouldCreateSO = true;

            AssetDatabase.Refresh();

            // Force repaint pour accélérer le polling
            Repaint();

            Debug.Log($"✅ Script généré : {fullScriptPath}");
        }

        void TryCreateAssetIfReady()
        {
            if (!_shouldCreateSO)
                return;

            // Attendre que Unity ait fini
            if (EditorApplication.isCompiling || EditorApplication.isUpdating)
                return;

            var type = GetTypeByName(_pendingClassName);
            if (type == null)
                return;

            // Vérifie qu’au moins un field existe
            var entry = _pendingTable.SharedData.Entries.FirstOrDefault();
            if (entry == null)
                return;

            var field = type.GetField(SanitizeKey(entry.Key), BindingFlags.Public | BindingFlags.Instance);
            if (field == null)
                return;

            Debug.Log("✅ READY → Création du ScriptableObject");

            _shouldCreateSO = false;

            CreateAndPopulateSO(_pendingClassName, _pendingTable, _pendingFolderPath);
        }

        Type GetTypeByName(string className)
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a => a.GetTypes())
                .FirstOrDefault(t => t.Name == className);
        }

        void CreateAndPopulateSO(string className, LocalizationTableCollection table, string folderPath)
        {
            var type = GetTypeByName(className);

            if (type == null)
            {
                Debug.LogError($"❌ Type {className} introuvable.");
                return;
            }

            string assetPath = Path.Combine(folderPath, $"{className}.asset");

            ScriptableObject asset = AssetDatabase.LoadAssetAtPath(assetPath, type) as ScriptableObject;

            if (asset == null)
            {
                asset = ScriptableObject.CreateInstance(type);
                AssetDatabase.CreateAsset(asset, assetPath);
                Debug.Log($"✅ Asset créé : {assetPath}");
            }

            // 1. Remplir les fields
            foreach (var entry in table.SharedData.Entries)
            {
                var field = type.GetField(SanitizeKey(entry.Key), BindingFlags.Public | BindingFlags.Instance);
                if (field == null) continue;

                if (table is StringTableCollection)
                {
                    var loc = field.GetValue(asset) as LocalizedString ?? new LocalizedString();
                    loc.TableReference = table.TableCollectionNameReference;
                    loc.TableEntryReference = entry.Key;
                    field.SetValue(asset, loc);
                }
                else
                {
                    var loc = field.GetValue(asset) as LocalizedAssetBase ??
                              Activator.CreateInstance(field.FieldType) as LocalizedAssetBase;

                    loc.TableReference = table.TableCollectionNameReference;
                    loc.TableEntryReference = entry.Key;
                    field.SetValue(asset, loc);
                }
            }

            // 2. Construire le tableau
            if (generateArray)
            {
                var allField = type.GetField("All", BindingFlags.Public | BindingFlags.Instance);

                if (allField != null)
                {
                    var elementType = allField.FieldType.GetElementType();
                    var array = Array.CreateInstance(elementType, table.SharedData.Entries.Count);

                    for (int i = 0; i < table.SharedData.Entries.Count; i++)
                    {
                        var entry = table.SharedData.Entries[i];
                        var field = type.GetField(SanitizeKey(entry.Key), BindingFlags.Public | BindingFlags.Instance);

                        if (field != null)
                            array.SetValue(field.GetValue(asset), i);
                    }

                    allField.SetValue(asset, array);
                }
            }

            // 3. Save
            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log("✅ ScriptableObject correctement peuplé (fields + array)");
        }

        string SanitizeKey(string key)
        {
            var sb = new StringBuilder();
            foreach (char c in key)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');

            if (char.IsDigit(sb[0]))
                sb.Insert(0, '_');

            return sb.ToString();
        }
    }
}