using LightHouse.Audio.AutoGenerated;
using LightHouse.Audio;
using System.Collections.Generic;
using System.IO;
using System;
using UnityEditor;
using UnityEngine;
using UnityEngine.Localization;
using System.Linq;
using UnityEditor.Localization;

namespace LightHouse.CustomEditors
{
    [CustomEditor(typeof(AudioDatabase))]
    public class AudioDatabaseEditor : Editor
    {
        private const string BasePath = "Assets/Databases/DB_Audio/AutoGeneratedFiles/";

        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();
            AudioDatabase audioDatabase = (AudioDatabase)target;

            if (GUILayout.Button("Find Assets & Refresh"))
            {
                var ambiances = FindAmbiancesAssets(audioDatabase.Ambiances);
                var effects = FindEffectsAssets(audioDatabase.Effects);
                var musics = FindMusicsAssets(audioDatabase.Musics);
                var dialogues = FindDialoguesAssets(audioDatabase.Dialogues);

                audioDatabase.Ambiances = ambiances;
                audioDatabase.Effects = effects;
                audioDatabase.Musics = musics;
                audioDatabase.Dialogues = dialogues;

                GenerateAmbiancesEnum(ambiances);
                GenerateEffectsEnum(effects);
                GenerateMusicsEnum(musics);
                GenerateDialogsEnum(dialogues);
                ApplySettingsToAsset(ambiances, effects, musics, dialogues);
                EditorUtility.SetDirty(target);
            }

            if (GUILayout.Button("Only Refresh"))
            {
                var ambiances = FindAmbiancesAssets(audioDatabase.Ambiances);
                var effects = FindEffectsAssets(audioDatabase.Effects);
                var musics = FindMusicsAssets(audioDatabase.Musics);
                var dialogues = FindDialoguesAssets(audioDatabase.Dialogues);

                GenerateAmbiancesEnum(ambiances);
                GenerateEffectsEnum(effects);
                GenerateMusicsEnum(musics);
                GenerateDialogsEnum(dialogues);
                ApplySettingsToAsset(ambiances, effects, musics, dialogues);
                EditorUtility.SetDirty(target);
            }
        }

        private void ApplySettingsToAsset(
            List<AmbianceAudio> ambianceAssets,
            List<EffectAudio> effectAssets,
            List<MusicAudio> musicAssets,
            List<LocalizedDialogueAudio> dialogueAssets)
        {
            foreach (var asset in ambianceAssets)
            {
                string sanitized = AudioUtils.SanitizeName(asset.displayName);
                if (Enum.TryParse(sanitized, out AmbianceAudioName parsed))
                    asset.Category = parsed;
                else
                    Debug.LogWarning($"[ApplySettings] Nom '{sanitized}' non trouvé dans l'enum AmbianceAudioName");

                EditorUtility.SetDirty(asset);
            }

            foreach (var asset in effectAssets)
            {
                string sanitized = AudioUtils.SanitizeName(asset.displayName);
                if (Enum.TryParse(sanitized, out EffectsAudioName parsed))
                    asset.Category = parsed;
                else
                    Debug.LogWarning($"[ApplySettings] Nom '{sanitized}' non trouvé dans l'enum EffectsAudioName");

                EditorUtility.SetDirty(asset);
            }

            foreach (var asset in musicAssets)
            {
                string sanitized = AudioUtils.SanitizeName(asset.displayName);
                if (Enum.TryParse(sanitized, out MusicsAudioName parsed))
                    asset.Category = parsed;
                else
                    Debug.LogWarning($"[ApplySettings] Nom '{sanitized}' non trouvé dans l'enum MusicsAudioName");

                EditorUtility.SetDirty(asset);
            }

            foreach (var asset in dialogueAssets)
            {
                /*string sanitized = AudioUtils.SanitizeName(GetEntryKey(asset.LocalizedSubtitle));
                if (Enum.TryParse(sanitized, out DialogueAudioName parsed))
                {
                    asset.Category = parsed;
                }
                else
                    Debug.LogWarning($"[ApplySettings] Nom '{sanitized}' non trouvé dans l'enum DialogueAudioName");

                EditorUtility.SetDirty(asset);*/
            }
        }

        // Génération des enums modifiée pour prendre en paramètre les listes
        private void GenerateAmbiancesEnum(List<AmbianceAudio> assets)
            => GenerateEnumFromAssets("AmbianceAudioName", assets.Select(a => a.displayName));

        private void GenerateEffectsEnum(List<EffectAudio> assets)
            => GenerateEnumFromAssets("EffectsAudioName", assets.Select(a => a.displayName));

        private void GenerateMusicsEnum(List<MusicAudio> assets)
            => GenerateEnumFromAssets("MusicsAudioName", assets.Select(a => a.displayName));

        private void GenerateDialogsEnum(List<LocalizedDialogueAudio> assets)
        {
            var names = new List<string>();
            foreach (var asset in assets)
            {
                string key = GetEntryKey(asset.SubtitleRef);
                if (!string.IsNullOrEmpty(key))
                {
                    string cleanName = AudioUtils.SanitizeName(key);
                    if (!names.Contains(cleanName))
                        names.Add(cleanName);
                }
            }

            GenerateEnumFile("DialogueAudioName", BasePath + "DialogueAudioName.cs", names);
        }

        private void GenerateEnumFromAssets(string enumName, IEnumerable<string> rawNames)
        {
            var names = new HashSet<string>().ToList();
            foreach (var raw in rawNames)
            {
                if (!string.IsNullOrEmpty(raw))
                {
                    string clean = AudioUtils.SanitizeName(raw);
                    names.Add(clean);
                }
            }
            GenerateEnumFile(enumName, BasePath + enumName + ".cs", names);
        }

        private void GenerateEnumFile(string enumName, string filePath, List<string> entries)
        {
            if (entries.Count == 0)
            {
                Debug.LogWarning($"No entries found for {enumName}");
                return;
            }

            var sb = new System.Text.StringBuilder();
            sb.AppendLine("/// <auto-generated/>");
            sb.AppendLine("namespace LightHouse.Audio.AutoGenerated");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            foreach (var entry in entries)
                sb.AppendLine($"        {entry},");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string newContent = sb.ToString();

            if (File.Exists(filePath))
            {
                string existingContent = File.ReadAllText(filePath);
                if (existingContent == newContent)
                {
                    Debug.Log($"{enumName} à jour — aucune modification nécessaire.");
                    return;
                }

                if (!EditorUtility.DisplayDialog("Fichier déjà existant",
                    $"Le fichier '{enumName}.cs' existe déjà. Voulez-vous le remplacer ?", "Oui", "Non"))
                {
                    return;
                }
            }

            Directory.CreateDirectory(Path.GetDirectoryName(filePath));
            File.WriteAllText(filePath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"{enumName} généré avec succès !");
        }


        private List<AmbianceAudio> FindAmbiancesAssets(List<AmbianceAudio> existingInManager) => LoadAssets<AmbianceAudio>(existingInManager);
        private List<EffectAudio> FindEffectsAssets(List<EffectAudio> existingInManager) => LoadAssets<EffectAudio>(existingInManager);
        private List<MusicAudio> FindMusicsAssets(List<MusicAudio> existingInManager) => LoadAssets<MusicAudio>(existingInManager);
        private List<LocalizedDialogueAudio> FindDialoguesAssets(List<LocalizedDialogueAudio> existingInManager) => LoadAssets<LocalizedDialogueAudio>(existingInManager);

        private List<T> LoadAssets<T>(List<T> existingList) where T : UnityEngine.Object
        {
            List<T> updatedList = new(existingList); // clone pour éviter de modifier directement
            HashSet<string> existingPaths = new(existingList.Select(AssetDatabase.GetAssetPath));

            string[] guids = AssetDatabase.FindAssets($"t:{typeof(T).Name}");
            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!existingPaths.Contains(path))
                {
                    T asset = AssetDatabase.LoadAssetAtPath<T>(path);
                    if (asset != null)
                    {
                        updatedList.Add(asset);
                        existingPaths.Add(path);
                    }
                }
            }

            return updatedList;
        }


        private string GetEntryKey(LocalizedString localizedString)
        {
            string tableName = localizedString.TableReference.TableCollectionName;
            long keyId = localizedString.TableEntryReference.KeyId;

            StringTableCollection table = LocalizationEditorSettings.GetStringTableCollection(tableName);
            if (table == null) return null;

            foreach (var entry in table.SharedData.Entries)
            {
                if (entry.Id == keyId)
                    return entry.Key;
            }

            return null;
        }
    }
}
