using LightHouse.Audio;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;
using System;

namespace LightHouse.CustomEditors
{
    [CustomEditor(typeof(AudioDatabase))]
    public class AudioDatabaseEditor : Editor
    {
        private const string BasePath = "Assets/Databases/DB_Audio/AutoGeneratedFiles/";
        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();
            AudioDatabase audioDatabase = (AudioDatabase)target;

            if (GUILayout.Button("Find All"))
            {
                audioDatabase.Ambiances = FindAmbiancesAssets();
                audioDatabase.Effects = FindEffectsAssets();
                audioDatabase.Musics = FindMusicsAssets();
                audioDatabase.Dialogues = FindDialoguesAssets();
                EditorUtility.SetDirty(target);
            }

            if (GUILayout.Button("Refresh Files All"))
            {
                GenerateAmbiancesEnum();
                GenerateEffectsEnum();
                GenerateMusicsEnum();
                GenerateDialoguesEnum();
            }

            if (GUILayout.Button("Apply Settings to SO"))
            {
                ApplySettingsToAsset();
            }
        }

        private void ApplySettingsToAsset()
        {
            var ambianceAssets = FindAmbiancesAssets();
            foreach (var asset in ambianceAssets)
            {
                string sanitized = SanitizeName(asset.displayName);
                if (System.Enum.TryParse<AmbianceAudioName>(sanitized, out var parsed))
                {
                    asset.Category = parsed;
                    EditorUtility.SetDirty(asset);
                }
                else
                {
                    Debug.LogWarning($"[ApplySettings] Nom '{sanitized}' non trouvé dans l'enum AmbianceAudioName");
                }
            }

            var effectAssets = FindEffectsAssets();
            foreach (var asset in effectAssets)
            {
                string sanitized = SanitizeName(asset.displayName);
                if (System.Enum.TryParse<EffectsAudioName>(sanitized, out var parsed))
                {
                    asset.Category = parsed;
                    EditorUtility.SetDirty(asset);
                }
                else
                {
                    Debug.LogWarning($"[ApplySettings] Nom '{sanitized}' non trouvé dans l'enum EffectsAudioName");
                }
            }

            var musicAssets = FindMusicsAssets();
            foreach (var asset in musicAssets)
            {
                string sanitized = SanitizeName(asset.displayName);
                if (System.Enum.TryParse<MusicsAudioName>(sanitized, out var parsed))
                {
                    asset.Category = parsed;
                    EditorUtility.SetDirty(asset);
                }
                else
                {
                    Debug.LogWarning($"[ApplySettings] Nom '{sanitized}' non trouvé dans l'enum AmbianceAudioName");
                }
            }
        }

        public List<AmbianceAudio> FindAmbiancesAssets()
        {
            string[] ambianceGuids = GetGuids("AmbianceAudio");

            List<AmbianceAudio> audiosAssets = new();
            foreach (string ambianceGuid in ambianceGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(ambianceGuid);
                AmbianceAudio asset = AssetDatabase.LoadAssetAtPath<AmbianceAudio>(path);
                audiosAssets.Add(asset);
            }
            return audiosAssets;
        }

        private List<LocalizedDialogueAudio> FindDialoguesAssets()
        {
            string[] effectsGuids = GetGuids("LocalizedDialogueAudio");

            List<LocalizedDialogueAudio> audiosAssets = new();
            foreach (string ambianceGuid in effectsGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(ambianceGuid);
                LocalizedDialogueAudio asset = AssetDatabase.LoadAssetAtPath<LocalizedDialogueAudio>(path);
                audiosAssets.Add(asset);
            }
            return audiosAssets;
        }

        public List<EffectAudio> FindEffectsAssets()
        {
            string[] effectsGuids = GetGuids("EffectAudio");

            List<EffectAudio> audiosAssets = new();
            foreach (string ambianceGuid in effectsGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(ambianceGuid);
                EffectAudio asset = AssetDatabase.LoadAssetAtPath<EffectAudio>(path);
                audiosAssets.Add(asset);
            }
            return audiosAssets;
        }

        public List<MusicAudio> FindMusicsAssets()
        {
            string[] effectsGuids = GetGuids("MusicAudio");

            List<MusicAudio> audiosAssets = new();
            foreach (string ambianceGuid in effectsGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(ambianceGuid);
                MusicAudio asset = AssetDatabase.LoadAssetAtPath<MusicAudio>(path);
                audiosAssets.Add(asset);
            }
            return audiosAssets;
        }

        public void GenerateAmbiancesEnum()
        {
            string enumName = "AmbianceAudioName";
            string filePath = BasePath + enumName + ".cs";

            // Trouver tous les assets AmbianceAudio
            string[] guids = AssetDatabase.FindAssets("t:AmbianceAudio");

            List<string> names = new List<string>();

            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                AmbianceAudio asset = AssetDatabase.LoadAssetAtPath<AmbianceAudio>(path);
                if (asset != null && !string.IsNullOrEmpty(asset.displayName))
                {
                    string cleanName = SanitizeName(asset.displayName);
                    if (!names.Contains(cleanName))
                        names.Add(cleanName);
                }
            }

            GenerateEnumFile(enumName, filePath, names);
        }

        private void GenerateDialoguesEnum()
        {
            string enumName = "DialogueAudioNames";
            string filePath = BasePath + enumName + ".cs";

            // Trouver tous les assets AmbianceAudio
            string[] guids = AssetDatabase.FindAssets("t:DialogueAudio");

            List<string> names = new List<string>();

            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                AmbianceAudio asset = AssetDatabase.LoadAssetAtPath<AmbianceAudio>(path);
                if (asset != null && !string.IsNullOrEmpty(asset.displayName))
                {
                    string cleanName = SanitizeName(asset.displayName);
                    if (!names.Contains(cleanName))
                        names.Add(cleanName);
                }
            }

            GenerateEnumFile(enumName, filePath, names);
        }


        public void GenerateEffectsEnum()
        {
            string enumName = "EffectsAudioName";
            string filePath = BasePath + enumName + ".cs";

            // Trouver tous les assets AmbianceAudio
            string[] guids = AssetDatabase.FindAssets("t:EffectAudio");

            List<string> names = new List<string>();

            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                EffectAudio asset = AssetDatabase.LoadAssetAtPath<EffectAudio>(path);
                if (asset != null && !string.IsNullOrEmpty(asset.displayName))
                {
                    string cleanName = SanitizeName(asset.displayName);
                    if (!names.Contains(cleanName))
                        names.Add(cleanName);
                }
            }

            GenerateEnumFile(enumName, filePath, names);
        }

        //
        public void GenerateMusicsEnum()
        {
            string enumName = "MusicsAudioName";
            string filePath = BasePath + enumName + ".cs";

            // Trouver tous les assets AmbianceAudio
            string[] guids = AssetDatabase.FindAssets("t:MusicAudio");

            List<string> names = new List<string>();

            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                MusicAudio asset = AssetDatabase.LoadAssetAtPath<MusicAudio>(path);
                if (asset != null && !string.IsNullOrEmpty(asset.displayName))
                {
                    string cleanName = SanitizeName(asset.displayName);
                    if (!names.Contains(cleanName))
                        names.Add(cleanName);
                }
            }

            GenerateEnumFile(enumName, filePath, names);
        }

        private string[] GetGuids(string assetName)
        {
            return AssetDatabase.FindAssets($"t:{assetName}");
        }

        private void GenerateEnumFile(string enumName, string filePath, List<string> entries)
        {
            if (entries.Count == 0)
            {
                Debug.LogWarning($"No entries found for {enumName}");
                return;
            }

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine("/// <auto-generated/>");
            sb.AppendLine("namespace LightHouse.Audio.AutoGenerated");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            foreach (string entry in entries)
            {
                sb.AppendLine($"        {entry},");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string newContent = sb.ToString();
            // Vérifie si le fichier existe et si le contenu est identique
            if (System.IO.File.Exists(filePath))
            {
                string existingContent = System.IO.File.ReadAllText(filePath);
                if (existingContent == newContent)
                {
                    Debug.Log($"{enumName} à jour — aucune modification nécessaire.");
                    return; // Rien à faire
                }
            }

            if (System.IO.File.Exists(filePath))
            {
                if (!EditorUtility.DisplayDialog("Fichier déjà existant",
                    $"Le fichier '{enumName}.cs' existe déjà. Voulez-vous le remplacer ?", "Oui", "Non"))
                {
                    return;
                }
            }

            // write the file
            System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(filePath));
            System.IO.File.WriteAllText(filePath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"{enumName} généré avec succès !");
        }

        private string SanitizeName(string rawName)
        {
            string clean = rawName.Replace(" ", "_")
                                  .Replace("-", "_")
                                  .Replace(".", "_");

            // Remove all non numerical characters
            clean = System.Text.RegularExpressions.Regex.Replace(clean, @"[^a-zA-Z0-9_]", "");

            return clean;
        }


    }

}
