using LightHouse.Audio.AutoGenerated;
using UnityEngine;

namespace LightHouse.Audio
{
    public class PlayAmbianceOnStart : MonoBehaviour
    {
        public AmbianceAudioName Category;
        private void Start()
        {
            AudioHandlerData.AudioManager.PlayAmbiance(this.transform, Category);

        }
    }
}
