using UnityEngine;
using LightHouse.Audio.AutoGenerated;

namespace LightHouse.Audio
{
    public class PlayMusicOnStart : MonoBehaviour
    {
       /* public MusicsAudioName Category;

        private void Start()
        {
            AudioHandlerData.AudioManager.PlayMusic(this.transform, Category);
        }*/
    }
}
