using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;

public class AudioManager : MonoBehaviour
{

    [SerializeField] private AudioDatabase _audioDB;

    private void Start()
    {
        AudioHandlerData.Initialize(this);
    }

    private void OnDestroy()
    {
        AudioHandlerData.Clear();
    }

    public void AttachAndPlay(Transform parent)
    {

    }
    private GameObject PlayClip(AudioClip clip, Transform parent, float volume, float spatialBlend, float pitch = 1.0f)
    {
        GameObject tempGO = new GameObject("TempAudio2D");
        if (spatialBlend != 0.0f)
        {
            tempGO.transform.SetParent(parent);
            tempGO.transform.position = parent.position;
        }
        AudioSource source = tempGO.AddComponent<AudioSource>();
        source.clip = clip;
        source.volume = volume;
        source.spatialBlend = spatialBlend; // 0 = 2D, 1 = 3D
        source.Play();
        Destroy(tempGO, clip.length);
        return tempGO;
    }
    private void PlayClip(AudioClip clip, Vector3 pos, float volume, float spatialBlend, float pitch = 1.0f)
    {
        GameObject tempGO = new GameObject("TempAudio2D");
        tempGO.transform.position = pos;
        AudioSource source = tempGO.AddComponent<AudioSource>();
        source.clip = clip;
        source.volume = volume;
        source.spatialBlend = spatialBlend; // 0 = 2D, 1 = 3D
        source.Play();
        Destroy(tempGO, clip.length);
    }


    public void PlayAmbiance(Transform parent, AmbianceAudioName category)
    {
        AmbianceAudio ambiance = _audioDB.GetAmbiance(category);
        if (ambiance == null)
        {
            Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
            return;
        }

        AudioClip clip = ambiance.GetRandomClip();
        if (clip == null)
        {
            Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
            return;
        }

        PlayClip(clip, parent, ambiance.volume, ambiance._spatialBlend);
        //AudioSource.PlayClipAtPoint(clip, position, ambiance.volume);
    }


    public void PlayEffect(Transform parent, EffectsAudioName category)
    {
        EffectAudio effect = _audioDB.GetEffect(category);
        if (effect == null)
        {
            Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
            return;
        }

        AudioClip clip = effect.GetRandomClip();
        if (clip == null)
        {
            Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
            return;
        }
        // Lecture du clip à la position spécifiée
        PlayClip(clip, parent, effect.volume, effect._spatialBlend);
    }

    public void PlayEffect(Vector3 pos, EffectsAudioName category)
    {
        EffectAudio effect = _audioDB.GetEffect(category);
        if (effect == null)
        {
            Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
            return;
        }

        AudioClip clip = effect.GetRandomClip();
        if (clip == null)
        {
            Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
            return;
        }
        
        PlayClip(clip, pos, effect.volume, effect._spatialBlend);
    }

    public float GetEffectLength(EffectsAudioName category, int clipIndex = 0)
    {
        var effect = _audioDB.GetEffect(category).clips[clipIndex];
        return effect.length;
    }

    public void PlayMusic(Transform parent, MusicsAudioName category)
    {
        MusicAudio music = _audioDB.GetMusic(category);
        if (music == null)
        {
            Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
            return;
        }

        AudioClip clip = music.GetRandomClip();
        if (clip == null)
        {
            Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
            return;
        }

        // Lecture du clip à la position spécifiée
        PlayClip(clip, parent, music.volume, music._spatialBlend);
    }

}
