using System.Collections.Generic;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;

[CreateAssetMenu(fileName = "AudioDB_", menuName = "LightHouse/Databases/Audio")]
public class AudioDatabase : ScriptableObject
{
    public List<AmbianceAudio> ambiances;
    public List<EffectAudio> effets;
    public List<MusicAudio> musics;

    public AmbianceAudio GetAmbiance(AmbianceAudioName category)
    {
        return ambiances.Find(a => a.Category == category);
    }

    public MusicAudio GetMusic(MusicsAudioName category)
    {
        return musics.Find(m => m.Category == category);
    }

    public EffectAudio GetEffect(EffectsAudioName category)
    {
        return effets.Find(e => e.Category == category);
    }
}
