using System.Collections;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;

public class AudioManager : MonoBehaviour
{

    [SerializeField] private AudioDatabase _audioDB;

    private void Awake()
    {
        AudioHandlerData.Initialize(this);
    }

    private void Start()
    {
        DontDestroyOnLoad(this.gameObject);
    }

    private void OnDestroy()
    {
        AudioHandlerData.Clear();
    }

    private AudioSource PlayClip(AudioClip clip, Transform parent, float volume, bool loop, float spatialBlend, float pitch = 1.0f)
    {
        GameObject tempGO = new GameObject("TempAudio2D");
        if (spatialBlend != 0.0f)
        {
            tempGO.transform.SetParent(parent);
            tempGO.transform.position = parent.position;
        }
        AudioSource source = tempGO.AddComponent<AudioSource>();
        source.clip = clip;
        source.loop = loop;
        source.volume = volume;
        source.spatialBlend = spatialBlend; // 0 = 2D, 1 = 3D
        source.Play();
        Destroy(tempGO, clip.length);
        return source;
    }
    private AudioSource PlayTempClip(AudioClip clip, Vector3 pos, float volume, float spatialBlend, float pitch = 1.0f)
    {
        GameObject tempGO = new GameObject("TempAudio2D");
        tempGO.transform.position = pos;
        AudioSource source = tempGO.AddComponent<AudioSource>();
        source.clip = clip;
        source.volume = volume;
        source.spatialBlend = spatialBlend; // 0 = 2D, 1 = 3D
        source.Play();
        Destroy(tempGO, clip.length);
        return source;
    }

    public AudioSource PlayMusic(Transform parent, MusicsAudioName category)
    {
        MusicAudio music = _audioDB.GetMusic(category);
        if (music == null)
        {
            Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
            return null;
        }

        AudioClip clip = music.GetRandomClip();
        if (clip == null)
        {
            Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
            return null;
        }

        // Lecture du clip à la position spécifiée
        return PlayClip(clip, parent, music.volume, music.loop, music._spatialBlend);
    }


    public AudioSource PlayAmbiance(Transform parent, AmbianceAudioName category)
    {
        AmbianceAudio ambiance = _audioDB.GetAmbiance(category);
        if (ambiance == null)
        {
            Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
            return null;
        }

        AudioClip clip = ambiance.GetRandomClip();
        if (clip == null)
        {
            Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
            return null;
        }

        return PlayClip(clip, parent, ambiance.volume, ambiance.loop, ambiance._spatialBlend);
    }


    public AudioSource PlayRandomEffect(Transform parent, EffectsAudioName category)
    {
        EffectAudio effect = _audioDB.GetEffect(category);
        if (effect == null)
        {
            Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
            return null;
        }

        AudioClip clip = effect.GetRandomClip();
        if (clip == null)
        {
            Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
            return null;
        }
        // Lecture du clip à la position spécifiée
        return PlayClip(clip, parent, effect.volume, effect.loop, effect._spatialBlend);
    }

    public AudioSource PlayRandomEffect(Vector3 pos, EffectsAudioName category)
    {
        EffectAudio effect = _audioDB.GetEffect(category);
        if (effect == null)
        {
            Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
            return null;
        }

        AudioClip clip = effect.GetRandomClip();
        if (clip == null)
        {
            Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
            return null;
        }
        
        return PlayTempClip(clip, pos, effect.volume, effect._spatialBlend);
    }

    public float GetEffectLength(EffectsAudioName category, int clipIndex = 0)
    {
        var effect = _audioDB.GetEffect(category).clips[clipIndex];
        return effect.length;
    }

}
