using System.Collections.Generic;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;

namespace LightHouse.Audio
{
    [CreateAssetMenu(fileName = "AudioDB_", menuName = "LightHouse/Databases/Audio")]
    public class AudioDatabase : ScriptableObject
    {
        public List<AmbianceAudio> Ambiances;
        public List<EffectAudio> Effects;
        public List<MusicAudio> Musics;
        public List<LocalizedDialogueAudio> Dialogues;

       /* public AmbianceAudio GetAmbiance(AmbianceAudioName category)
        {
            return Ambiances.Find(a => a.Category == category);
        }

        public MusicAudio GetMusic(MusicsAudioName category)
        {
            return Musics.Find(m => m.Category == category);
        }

        public EffectAudio GetEffect(EffectsAudioName category)
        {
            return Effects.Find(e => e.Category == category);
        }

        public LocalizedDialogueAudio GetDialogue(DialogueAudioName category)
        {
            return Dialogues.Find(e => e.Category == category);
        }*/
    }
}
