using LightHouse.Audio.AutoGenerated;
using UnityEngine;

public class PlayAmbianceOnStart : MonoBehaviour
{
    public AmbianceAudioName Category;
    private void Start()
    {
        AudioHandlerData.AudioManager.PlayAmbiance(this.transform, Category);

    }
}
