using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;
using System.Threading.Tasks;

public class PlayMusicOnStart : MonoBehaviour
{
    public MusicsAudioName Category;

    private void Start()
    {
        AudioHandlerData.AudioManager.PlayMusic(this.transform, Category);
    }
}
