using LightHouse.Audio.AutoGenerated;
using UnityEngine;

public class PlayAmbianceOnStart : MonoBehaviour
{
    public AmbianceAudioName Category;

    private void Awake()
    {
        AudioHandlerData.OnAudioManagerInitialized += AudioHandlerData_OnAudioManagerInitialized;
    }

    private void OnDestroy()
    {
        AudioHandlerData.OnAudioManagerInitialized -= AudioHandlerData_OnAudioManagerInitialized;
    }

    private void AudioHandlerData_OnAudioManagerInitialized()
    {
        AudioHandlerData.AudioManager.PlayAmbiance(this.transform, Category);
    }
}
