using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;

public class PlayMusicOnStart : MonoBehaviour
{
    public MusicsAudioName Category;

    private void Awake()
    {
        AudioHandlerData.OnAudioManagerInitialized += AudioHandlerData_OnAudioManagerInitialized;
    }

    private void OnDestroy()
    {
        AudioHandlerData.OnAudioManagerInitialized -= AudioHandlerData_OnAudioManagerInitialized;
    }

    private void AudioHandlerData_OnAudioManagerInitialized()
    {
        AudioHandlerData.AudioManager.PlayMusic(this.transform, Category);
    }
}
