using LightHouse.Inputs;
using LightHouse.Inventory;
using System;
using UnityEngine;

namespace LightHouse.Items
{
    public class FlashLight : InventoryItemBase, IInventoryItemUsable
    {
        [Header("IInventory Item")]
        public bool CanBeUsedFromInventory { get; set; } = true;
        public event Action OnItemUsed;
        public event Action<ushort, ushort> CanBeUsedFromInventoryChanged;
        private bool _isLightOn = false;
        [SerializeField] private Light _light;

        private void Awake()
        {
            _isLightOn = false;
            _light.gameObject.SetActive(false);
        }

        public void On()
        {
            _isLightOn = true;
            _light.gameObject.SetActive(true);
            AudioHandlerData.AudioManager.PlayRandomEffect(this.transform, LightHouse.Audio.AutoGenerated.EffectsAudioName.Effect_FlashlightOn);
        }

        public void Off()
        {
            _isLightOn = false;
            _light.gameObject.SetActive(false);
            AudioHandlerData.AudioManager.PlayRandomEffect(this.transform, LightHouse.Audio.AutoGenerated.EffectsAudioName.Effect_FlashlightOff);
        }

        //IInventoryUSable
        public string UseInInventoryText()
        {
            return _isLightOn ? $"Hold {InputManager.GetBindingName(InputManager.InteractInInventory)} to turn off"
             : $"Hold {InputManager.GetBindingName(InputManager.InteractInInventory)} to turn on";
        }

        public void UseFromInventory()
        {
            if (_isLightOn)
                Off();
            else
                On();
            UpdateUseInInventoryAtSlot(UseInInventoryText());
        }

        public void InvokeOnCanBeUsedFromInventoryChanged()
        {
            CanBeUsedFromInventoryChanged?.Invoke(this.GlobalItemID, this.ItemSpecificID);
        }

        public void UpdateUseInInventoryAtSlot(string newText)
        {
            if (SlotManager.FindItemInSlot(this.GlobalItemID, this.ItemSpecificID, out byte slotID))
            {
                SlotManager.Slots[slotID].SetUseKeyText(newText);
            }
        }
    }
}

