using LightHouse.Audio;
using LightHouse.Items.Inventory;
using System;
using System.Collections;
using UnityEngine;

namespace LightHouse.Items.Interactable
{
    public class Generator : MonoBehaviour
    {
        #region FIELDS
        [Header("Fuel Settings")]
        [SerializeField] private float _fuelLevel = 0f;
        [SerializeField] private float _fuelDecrementationSpeed = 1.0f;

        [Header("Audio")]
        [SerializeField] private AudioCue _startGeneratorSound;
        [SerializeField] private AudioCue _runningGeneratorSound;
        [SerializeField] private AudioCue _stopGeneratorSound;

        [Header("DEBUG")]
        [SerializeField] private bool _isGeneratorOn;
        [SerializeField] private InteractableSwitch _generatorSwitch;
        [SerializeField] private SingleRaycastedItemName _fuelIsRequired;
        [SerializeField] private JerricanItemTracker _jerricanReceiver;
        [SerializeField] private InteractableSwitch _fuelFillerLID;

        public AudioSource _autoGeneratedGeneratorRunningSource;

        private JerricanEssence _lastJerricanSelected;

        public event Action OnFuelDown;
        public event Action<bool> OnGeneratorSwitchChanged;
        #endregion

        #region PROPERTIES
        public bool IsGeneratorOn
        {
            get => _isGeneratorOn;
            private set
            {
                _isGeneratorOn = value;
                OnGeneratorSwitchChanged?.Invoke(value);
            }
        }
        #endregion

        #region MONO'S Callbacks

        private void Awake()
        {
            RegisterCallbacks();
            Initialize();
        }

        private void Update()
        {
            if (_isGeneratorOn)
            {
                _fuelLevel -= Time.deltaTime * _fuelDecrementationSpeed;

                if (_fuelLevel <= 0f)
                {
                    OnGeneratorFuelDown();
                    OnFuelDown?.Invoke();
                }
            }
        }

        private void OnDestroy()
        {
            UnregisterCallbacks();
        }

        #endregion

        #region INITIALIZE

        private void Initialize()
        {
            _fuelIsRequired.gameObject.SetActive(_fuelLevel > 0 ? false : true);
        }

        #endregion

        #region REGISTERING CALLBACKS
        private void RegisterCallbacks()
        {
            _generatorSwitch.OnObjectInteracted += GeneratorSwitch_OnObjectInteracted;
            _jerricanReceiver.OnJerricanUsed += JerricanReceiver_OnJerricanUsed;
            _fuelFillerLID.OnObjectInteracted += FuelFillerLID_OnObjectInteracted;
        }

        private void FuelFillerLID_OnObjectInteracted()
        {
            if(_fuelFillerLID.IsSwitchOn)
                _jerricanReceiver.gameObject.SetActive(true);
            else
                _jerricanReceiver.gameObject.SetActive(false);
        }

        private void UnregisterCallbacks()
        {
            _generatorSwitch.OnObjectInteracted -= GeneratorSwitch_OnObjectInteracted;
            _jerricanReceiver.OnJerricanUsed -= JerricanReceiver_OnJerricanUsed;
            _fuelFillerLID.OnObjectInteracted -= FuelFillerLID_OnObjectInteracted;
        }

        #endregion

        #region CONTROLLERS CALLBACKS
        private void JerricanReceiver_OnJerricanUsed(float essenceAmount)
        {
            AddFuel(essenceAmount);
        }

        private void GeneratorSwitch_OnObjectInteracted()
        {
            if(!_isGeneratorOn && _fuelLevel > 0f && _generatorSwitch.IsSwitchOn)
            {
                StartGenerator();
            }
            else if(_isGeneratorOn && !_generatorSwitch.IsSwitchOn)
            {
                StopGenerator();
            }
        }
        #endregion

        #region GENERATOR FUNCTIONS

        public void StartGenerator()
        {
            if (_isStarting) return; // empêche le spam

            _isStarting = true;
            IsGeneratorOn = true;
            _jerricanReceiver.gameObject.SetActive(true);

            float seconds = 0f;
            if (ServiceLocator.Audio != null && _startGeneratorSound != null)
            {
                IAudioHandle audioInfos = ServiceLocator.Audio.PlayAt(_startGeneratorSound, this.transform.position);
                seconds = audioInfos.SelectedClip.length - 0.15f;
            }

            StartCoroutine(DelayRoutine(seconds));
        }


        public IEnumerator DelayRoutine(float delay)
        {
            yield return new WaitForSeconds(delay);
            if(ServiceLocator.Audio != null && _runningGeneratorSound != null)
            {
                AudioHandle s = ServiceLocator.Audio.PlayAt(_runningGeneratorSound, this.transform.position) as AudioHandle;
                _autoGeneratedGeneratorRunningSource = s.CurrentSource;
            }
            _isStarting = false;
        }

        private bool _isStarting = false;

        public void StopGenerator()
        {
            if (_isStarting)
            {
                StopAllCoroutines(); // empêche la suite de DelayRoutine()
                _isStarting = false;
            }

            IsGeneratorOn = false;

            if (_autoGeneratedGeneratorRunningSource != null)
            {
                Destroy(_autoGeneratedGeneratorRunningSource.gameObject);
                _autoGeneratedGeneratorRunningSource = null;
            }

            if (ServiceLocator.Audio != null && _stopGeneratorSound != null)
                ServiceLocator.Audio.PlayAt(_stopGeneratorSound, this.transform.position);
        }


        private void OnGeneratorFuelDown()
        {
            _fuelLevel = 0f;
            StopGenerator();
        }

        public void SetFuel(float fuelValue)
        {
            _fuelLevel = fuelValue;
            OnFuelChanged();
        }

        public void AddFuel(float fuelValue) 
        {
            _fuelLevel += fuelValue;
            OnFuelChanged();
        }

        public void OnFuelChanged()
        {
            if(_fuelLevel > 0f && _fuelIsRequired.isActiveAndEnabled)
            {
                _fuelIsRequired.gameObject.SetActive(false);
            }
            else if(_fuelLevel <= 0f && !_fuelIsRequired.isActiveAndEnabled)
            {
                _fuelIsRequired.gameObject.SetActive(true);
            }
        }

        #endregion
    }

}
