using UnityEngine;
using LightHouse.Audio.AutoGenerated;

namespace LightHouse.Audio
{
    public class AudioManager : MonoBehaviour
    {
        [SerializeField] private AudioDatabase _audioDB;
        public AudioDatabase AudioDatabase => _audioDB;

        private void Awake()
        {
            foreach(var audio in _audioDB.Dialogues)
            {
                audio.Register();
            }
            AudioHandlerData.Initialize(this);
        }

        private void Start()
        {
            DontDestroyOnLoad(this.gameObject);
        }

        private void OnDestroy()
        {
            foreach (var audio in _audioDB.Dialogues)
            {
                audio.Unregister();
            }
            AudioHandlerData.Clear();
        }

        private AudioSource PlayClip(AudioClip clip, Transform parent, float volume, bool loop, float spatialBlend, float pitch = 1.0f)
        {
            string tempName = spatialBlend == 0.0f ? "TempAudio2D" : "TempAudio3D";
            GameObject tempGO = new GameObject(tempName);

            if (spatialBlend != 0.0f)
            {
                tempGO.transform.SetParent(parent);
                tempGO.transform.position = parent.position;
            }
            AudioSource source = tempGO.AddComponent<AudioSource>();
            source.clip = clip;
            source.loop = loop;
            source.pitch = pitch;
            source.volume = volume;
            source.spatialBlend = spatialBlend; // 0 = 2D, 1 = 3D
            source.Play();
            Destroy(tempGO, clip.length);
            return source;
        }
        private AudioSource PlayTempClip(AudioClip clip, Vector3 pos, float volume, float spatialBlend, float pitch = 1.0f)
        {
            string tempName = spatialBlend == 0.0f ? "TempAudio2D" : "TempAudio3D";
            GameObject tempGO = new GameObject(tempName);
            tempGO.transform.position = pos;
            AudioSource source = tempGO.AddComponent<AudioSource>();
            source.clip = clip;
            source.pitch = pitch;
            source.volume = volume;
            source.spatialBlend = spatialBlend; // 0 = 2D, 1 = 3D
            source.Play();
            Destroy(tempGO, clip.length);
            return source;
        }

        public AudioSource PlayMusic(Transform parent, MusicsAudioName category)
        {
            MusicAudio music = _audioDB.GetMusic(category);
            if (music == null)
            {
                Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
                return null;
            }

            AudioClip clip = music.GetRandomClip();
            if (clip == null)
            {
                Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
                return null;
            }

            // Lecture du clip à la position spécifiée
            return PlayClip(clip, parent, music.volume, music.loop, music._spatialBlend);
        }


        public AudioSource PlayAmbiance(Transform parent, AmbianceAudioName category)
        {
            AmbianceAudio ambiance = _audioDB.GetAmbiance(category);
            if (ambiance == null)
            {
                Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
                return null;
            }

            AudioClip clip = ambiance.GetRandomClip();
            if (clip == null)
            {
                Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
                return null;
            }

            return PlayClip(clip, parent, ambiance.volume, ambiance.loop, ambiance._spatialBlend);
        }


        public AudioSource PlayRandomEffect(Transform parent, EffectsAudioName category)
        {
            EffectAudio effect = _audioDB.GetEffect(category);
            if (effect == null)
            {
                Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
                return null;
            }

            AudioClip clip = effect.GetRandomClip();
            if (clip == null)
            {
                Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
                return null;
            }
            // Lecture du clip à la position spécifiée
            return PlayClip(clip, parent, effect.volume, effect.loop, effect._spatialBlend);
        }

        public AudioSource PlayRandomEffect(Vector3 pos, EffectsAudioName category)
        {
            EffectAudio effect = _audioDB.GetEffect(category);
            if (effect == null)
            {
                Debug.LogWarning($"[AudioManager] Ambiance '{category}' introuvable !");
                return null;
            }

            AudioClip clip = effect.GetRandomClip();
            if (clip == null)
            {
                Debug.LogWarning($"[AudioManager] Aucun clip trouvé pour l’ambiance '{category}'");
                return null;
            }

            return PlayTempClip(clip, pos, effect.volume, effect._spatialBlend);
        }

        public float GetEffectLength(EffectsAudioName category, int clipIndex = 0)
        {
            var effect = _audioDB.GetEffect(category).clips[clipIndex];
            return effect.length;
        }

        public LocalizedDialogueAudio PlayDialogueAt(AudioSource source, DialogueAudioName category)
        {
            var dialogue = _audioDB.GetDialogue(category);
            if (dialogue == null)
            {
                Debug.LogWarning($"[AudioManager] Dialogue '{category}' introuvable !");
                return null;
            }

            var clip = dialogue.CurrentAudioClip;
            if (clip == null)
            {
                Debug.LogWarning($"[AudioManager] Aucun clip pour le dialogue '{category}' !");
                return null;
            }

            source.clip = clip;
            source.loop = dialogue.Loop;
            //source.pitch = dialogue.pitch;
            source.volume = dialogue.Volume;
            source.spatialBlend = dialogue.SpatialBlend; // 0 = 2D, 1 = 3D
            source.Play();
            return dialogue;
        }

        public void PlayDialogueAt(AudioSource source, LocalizedDialogueAudio dialogue)
        {
            var clip = dialogue.CurrentAudioClip;
            if (clip == null)
            {
                Debug.LogWarning($"[AudioManager] Aucun clip pour le dialogue '{dialogue.Category}' !");
                return;
            }

            source.clip = clip;
            source.loop = dialogue.Loop;
            //source.pitch = dialogue.pitch;
            source.volume = dialogue.Volume;
            source.spatialBlend = dialogue.SpatialBlend; // 0 = 2D, 1 = 3D
            source.Play();
        }


    }

}
