using LightHouse.Audio.AutoGenerated;
using LightHouse.Game.Talkie;
using LightHouse.Interactions;
using UnityEngine;

namespace LightHouse.Items
{
    public class SingleTalkieRaycast : SingleRaycastedItemName, IItemCallback
    {
        [SerializeField] private TalkieServiceReference _service;
        [SerializeField] private DialogueAudioName DialogueToPlay;

        public void OnRaycastStart()
        {
            _service.Current.Enqueue(DialogueToPlay);
            this.gameObject.SetActive(false);
        }

        public void OnRaycastEnd()
        {
            
        }
    }
}
