using LightHouse.Audio.AutoGenerated;
using LightHouse.Game.Talkie;
using LightHouse.Interactions;
using UnityEngine;

namespace LightHouse.Items
{
    public class SingleTalkieRaycast : SingleRaycastedItemName, IItemCallback
    {
        [SerializeField] private TalkieServiceReference _service;
        [SerializeField] private DialogueAudioName[] DialogueToPlay;

        public void OnRaycastStart()
        {
            foreach(var dialogue in DialogueToPlay)
            {
                _service.Current.Enqueue(dialogue);
            }
            
            this.gameObject.SetActive(false);
        }

        public void OnRaycastEnd()
        {
            
        }
    }
}
