using System;
using System.Collections;
using System.Collections.Generic;
using LightHouse.Audio;
using LightHouse.Audio.AutoGenerated;
using LightHouse.Localization;
using TMPro;
using UnityEngine;

namespace LightHouse.Game.Talkie
{
    public class TalkieManager : MonoBehaviour, ITalkieService
    {
        public static Action ForceTalkiePlay;
        [SerializeField] private TalkieServiceReference _talkieServiceReference;
        [SerializeField] private AudioSource _audioSource;
        [SerializeField] private LocalizedStringDatabase_Talkie_Sentences _talkieSentencesDB;
        [SerializeField] private LocalizedDatabase_Talkie_Audio _talkieAudioDB;
        [SerializeField] private TextMeshProUGUI _radioTMP;
        [SerializeField] private CanvasGroup _radioDialog;

        [Header("Affichage")]
        [SerializeField] private float displayDuration = 3f;
        [SerializeField] private float fadeDuration = 0.5f;

        private readonly Queue<LocalizedDialogueAudio> _dialogueQueue = new();
        private bool _isPlaying;

        private void Awake()
        {
            BootStrap.BootStrap.OnGameAssetsLoaded += BootStrap_OnGameAssetsLoaded;
            _talkieServiceReference.Register(this);
        }

        private void OnDestroy()
        {
            _talkieServiceReference.ResetService();
            BootStrap.BootStrap.OnGameAssetsLoaded -= BootStrap_OnGameAssetsLoaded;
        }

        private void BootStrap_OnGameAssetsLoaded()
        {
            Enqueue(DialogueAudioName.TUTORIAL_TEST);
            Enqueue(DialogueAudioName.LONGSPEECH_TEST);
        }

        private IEnumerator ProcessTalkieQueue()
        {
            _isPlaying = true;

            while (_dialogueQueue.Count > 0)
            {
                LocalizedDialogueAudio dialogue = _dialogueQueue.Dequeue();
                AudioHandlerData.AudioManager.PlayDialogueAt(_audioSource, dialogue);
                yield return DisplayRadioText(dialogue.CurrentSubtitleText, dialogue.GetDisplayDuration(), dialogue.CharDelay);
            }

            _isPlaying = false;
        }

        private IEnumerator DisplayRadioText(string fullText, float audioDuration, float charDelay = 0.06f)
        {
            _radioTMP.text = "";
            _radioDialog.alpha = 0f;

            float remainingDisplayTime = Mathf.Max(displayDuration, audioDuration) - (fullText.Length * charDelay);

            WaitForSeconds textWFS = new WaitForSeconds(charDelay);
            WaitForSeconds remainDisplayTimeWTS = new WaitForSeconds(remainingDisplayTime);

            float t = 0f;
            while (t < fadeDuration)
            {
                _radioDialog.alpha = Mathf.Lerp(0f, 1f, t / fadeDuration);
                t += Time.deltaTime;
                yield return null;
            }
            _radioDialog.alpha = 1f;

            if(charDelay <= 0f)
            {
                _radioTMP.text = fullText;
            }
            else
            {
                for (int i = 0; i <= fullText.Length; i++)
                {
                    _radioTMP.text = fullText.Substring(0, i);
                    yield return textWFS;
                }
            }

            if (remainingDisplayTime > 0)
                yield return remainDisplayTimeWTS;

            // Fade-out
            t = 0f;
            while (t < fadeDuration)
            {
                _radioDialog.alpha = Mathf.Lerp(1f, 0f, t / fadeDuration);
                t += Time.deltaTime;
                yield return null;
            }

            _radioDialog.alpha = 0f;
            _radioTMP.text = "";
        }

        public void Enqueue(DialogueAudioName dialogueId)
        {
            LocalizedDialogueAudio dialogue = AudioHandlerData.AudioManager.AudioDatabase.GetDialogue(dialogueId);
            if (dialogue == null)
            {
                Debug.LogWarning($"[Talkie] Dialogue '{dialogueId}' introuvable.");
                return;
            }

            _dialogueQueue.Enqueue(dialogue);

            if (!_isPlaying)
            {
                StartCoroutine(ProcessTalkieQueue());
            }
        }
    }
}
