using System;
using System.Collections;
using System.Collections.Generic;
using LightHouse.Audio;
using LightHouse.Audio.AutoGenerated;
using LightHouse.Game.BootStrap;
using LightHouse.Localization;
using TMPro;
using UnityEngine;

namespace LightHouse.Game.Talkie
{
    public class TalkieManager : MonoBehaviour
    {
        public static Action ForceTalkiePlay;

        [SerializeField] private AudioSource _audioSource;
        [SerializeField] private LocalizedStringDatabase_Talkie_Sentences _talkieSentencesDB;
        [SerializeField] private LocalizedDatabase_Talkie_Audio _talkieAudioDB;
        [SerializeField] private TextMeshProUGUI _radioTMP;
        [SerializeField] private CanvasGroup _radioDialog;

        [Header("Affichage")]
        [SerializeField] private float displayDuration = 3f;
        [SerializeField] private float fadeDuration = 0.5f;

        private readonly Queue<LocalizedDialogueAudio> _dialogueQueue = new();
        private bool _isPlaying;

        private void Awake()
        {
            BootStrap.BootStrap.OnGameAssetsLoaded += BootStrap_OnGameAssetsLoaded;
        }

        private void OnDestroy()
        {
            BootStrap.BootStrap.OnGameAssetsLoaded -= BootStrap_OnGameAssetsLoaded;
        }

        private void BootStrap_OnGameAssetsLoaded()
        {
            EnqueueTalkie(DialogueAudioName.TUTORIAL_TEST);
            EnqueueTalkie(DialogueAudioName.LONGSPEECH_TEST);
        }

        public void EnqueueTalkie(DialogueAudioName id)
        {
            var dialogue = AudioHandlerData.AudioManager.AudioDatabase.GetDialogue(id);
            if (dialogue == null)
            {
                Debug.LogWarning($"[Talkie] Dialogue '{id}' introuvable.");
                return;
            }

            _dialogueQueue.Enqueue(dialogue);

            if (!_isPlaying)
            {
                StartCoroutine(ProcessTalkieQueue());
            }
        }

        private IEnumerator ProcessTalkieQueue()
        {
            _isPlaying = true;

            while (_dialogueQueue.Count > 0)
            {
                var dialogue = _dialogueQueue.Dequeue();

                // Lecture audio
                AudioHandlerData.AudioManager.PlayDialogueAt(_audioSource, dialogue.Category);

                // Affichage texte
                yield return DisplayRadioText(dialogue.currentSubtitle, dialogue.currentAudio.length);
            }

            _isPlaying = false;
        }

        private IEnumerator DisplayRadioText(string fullText, float audioDuration, float charDelay = 0.06f)
        {
            _radioTMP.text = "";
            _radioDialog.alpha = 0f;

            float remainingDisplayTime = Mathf.Max(displayDuration, audioDuration) - (fullText.Length * charDelay);

            WaitForSeconds textWFS = new WaitForSeconds(charDelay);
            WaitForSeconds remainDisplayTimeWTS = new WaitForSeconds(remainingDisplayTime);

            float t = 0f;
            while (t < fadeDuration)
            {
                _radioDialog.alpha = Mathf.Lerp(0f, 1f, t / fadeDuration);
                t += Time.deltaTime;
                yield return null;
            }
            _radioDialog.alpha = 1f;

            for (int i = 0; i <= fullText.Length; i++)
            {
                _radioTMP.text = fullText.Substring(0, i);
                yield return textWFS;
            }

            if (remainingDisplayTime > 0)
                yield return remainDisplayTimeWTS;

            // Fade-out
            t = 0f;
            while (t < fadeDuration)
            {
                _radioDialog.alpha = Mathf.Lerp(1f, 0f, t / fadeDuration);
                t += Time.deltaTime;
                yield return null;
            }

            _radioDialog.alpha = 0f;
            _radioTMP.text = "";
        }




    }
}
