using LightHouse.Audio.AutoGenerated;
using LightHouse.Game.Talkie;
using LightHouse.Items.Interactable;
using LightHouse.Utilities;
using UnityEngine;

namespace LightHouse.Game.Tutorial
{
    public class TutorialManager : MonoBehaviour
    {
        [SerializeField] private TalkieServiceReference _talkieRef;
        [SerializeField] private RopePlaceHolder _ropePlaceHolder;
        [SerializeField] private TriggerEvent _mainEntranceDoorTrigger;

        private bool _hasDoorBeenUnlockedForTheFirstTime = false;
        [SerializeField] private LockedDoor _lockedDoor;

        private void Awake()
        {
            _ropePlaceHolder.OnItemUsedOnMe += RopePlaceHolder_OnObjectInteracted;
            _mainEntranceDoorTrigger.OnEntered += MainEntranceDoorTrigger_OnEntered;
            _lockedDoor.OnObjectInteracted += LockedDoor_OnObjectInteracted;
        }

        private void Start()
        {
            _talkieRef.Current.Enqueue(DialogueAudioName.TUTORIAL_BoatArrival);
            _talkieRef.Current.Enqueue(DialogueAudioName.TUTORIAL_RopeAttach);

        }

        private void OnDestroy()
        {
            _mainEntranceDoorTrigger.OnEntered -= MainEntranceDoorTrigger_OnEntered;
            _ropePlaceHolder.OnItemUsedOnMe -= RopePlaceHolder_OnObjectInteracted;
            _lockedDoor.OnObjectInteracted -= LockedDoor_OnObjectInteracted;
        }

        private void RopePlaceHolder_OnObjectInteracted()
        {
            _talkieRef.Current.Enqueue(DialogueAudioName.TUTORIAL_EnterLighthouse);
        }

        private void MainEntranceDoorTrigger_OnEntered(GameObject obj)
        {
            _talkieRef.Current.Enqueue(DialogueAudioName.TUTORIAL_FindMainKey);
            _talkieRef.Current.Enqueue(DialogueAudioName.TUTORIAL_FindMainKey_2);
            _mainEntranceDoorTrigger.gameObject.SetActive(false);
            _mainEntranceDoorTrigger.Colllider.enabled = false;
        }

        private void LockedDoor_OnObjectInteracted()
        {
            if (_hasDoorBeenUnlockedForTheFirstTime) return;
            _hasDoorBeenUnlockedForTheFirstTime = true;
            _talkieRef.Current.Enqueue(DialogueAudioName.TUTORIAL_ElectricCurrent);
            _talkieRef.Current.Enqueue(DialogueAudioName.TUTORIAL_ElectricCurrent_2);
        }
    }

}
