using System;
using LightHouse.Game.Options;
using UnityEngine;
using UnityEngine.Localization.Settings;
using UnityEngine.UIElements;
using LightHouse.Localization;
using LightHouse.Audio;

namespace LightHouse.Game.Menu
{
    public class MainMenuController : MonoBehaviour
    {
        public UIDocument uiDoc;

        private VisualElement _menu_Root;
        private VisualElement _options_Root;

        [SerializeField] private OptionsMenuController _optionsMenuController;
        [SerializeField] private LocalizedStringDatabase_Menu_Main _mainMenuTextsDB;

        private Label _playLabel;
        private Label _settingsLabel;
        private Label _extrasLabel;
        private Label _quitLabel;
        private void Awake()
        {
            var root = uiDoc.rootVisualElement;
            _menu_Root = root.Q<VisualElement>("MainMenu_Root");
            _options_Root = root.Q<VisualElement>("Options_Root");

            RegisterButton(root.Q<VisualElement>("PlayButton"), Play);
            RegisterButton(root.Q<VisualElement>("SettinsButton"), Settings);
            RegisterButton(root.Q<VisualElement>("ExtrasButton"), Extras);
            RegisterButton(root.Q<VisualElement>("QuitButtons"), Quit);

            _playLabel = root.Q<Label>("PlayLabel");
            _settingsLabel = root.Q<Label>("SettingsLabel");
            _extrasLabel = root.Q<Label>("ExtrasLabel");
            _quitLabel = root.Q<Label>("QuitLabel");

            LocalizationSettings.SelectedLocaleChanged += LocalizationSettings_SelectedLocaleChanged;
            _optionsMenuController.OnBackClicked += OptionsMenuController_OnBackClicked;
        }

        private void Start()
        {
            UpdateLabels();
        }

        private void LocalizationSettings_SelectedLocaleChanged(UnityEngine.Localization.Locale obj)
        {
            UpdateLabels();
        }

        private void UpdateLabels()
        {
            _playLabel.text = _mainMenuTextsDB.PLAY.GetLocalizedString();
            _settingsLabel.text = _mainMenuTextsDB.SETTINGS.GetLocalizedString();
            _extrasLabel.text = _mainMenuTextsDB.EXTRAS.GetLocalizedString();
            _quitLabel.text = _mainMenuTextsDB.QUIT.GetLocalizedString();
        }

        private void OnDestroy()
        {
            LocalizationSettings.SelectedLocaleChanged -= LocalizationSettings_SelectedLocaleChanged;
            _optionsMenuController.OnBackClicked -= OptionsMenuController_OnBackClicked;
        }

        private void OptionsMenuController_OnBackClicked()
        {
            _menu_Root.style.display = DisplayStyle.Flex;
            _options_Root.style.display = DisplayStyle.None;
        }
        private void RegisterButton(VisualElement button, System.Action callback)
        {
            var fill = button.Q(className: "menu-fill");

            button.RegisterCallback<PointerEnterEvent>
                (_ =>
                {
                    if (!button.enabledInHierarchy) return;
                    AudioHandlerData.AudioManager.PlayRandomEffect(transform, LightHouse.Audio.AutoGenerated.EffectsAudioName.Effect_ButtonHover);
                    fill.style.width = new StyleLength(Length.Percent(100));
                }
                );

            button.RegisterCallback<PointerLeaveEvent>(_ =>
                fill.style.width = new StyleLength(Length.Percent(0)));

            button.RegisterCallback<ClickEvent>(_ =>
            {
                AudioHandlerData.AudioManager.PlayRandomEffect(transform, LightHouse.Audio.AutoGenerated.EffectsAudioName.Effect_ButtonCliqued);
                callback.Invoke();
            });
        }

        private void Play()
        {
            BootStrap.BootStrap.Instance.StartGame();
        }

        private void Settings()
        {
            _options_Root.style.display = DisplayStyle.Flex;
            _menu_Root.style.display = DisplayStyle.None;
        }

        private void Extras()
        {
            throw new NotImplementedException();
        }

        private void Quit()
        {
            Application.Quit();
        }
    }
}

