using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;

public class MainMenuController : MonoBehaviour
{
    public UIDocument uiDoc;

    private void Awake()
    {
        var root = uiDoc.rootVisualElement;

        RegisterButton(root.Q<VisualElement>("PlayButton"), Play);
        RegisterButton(root.Q<VisualElement>("SettinsButton"), Settings);
        RegisterButton(root.Q<VisualElement>("ExtrasButton"), Extras);
        RegisterButton(root.Q<VisualElement>("QuitButtons"), Quit);
    }

    private void RegisterButton(VisualElement button, System.Action callback)
    {
        var fill = button.Q(className: "menu-fill");

        button.RegisterCallback<PointerEnterEvent>
            (_ =>
                {
                    AudioHandlerData.AudioManager.PlayRandomEffect(transform, LightHouse.Audio.AutoGenerated.EffectsAudioName.Effect_ButtonHover);
                    fill.style.width = new StyleLength(Length.Percent(100));
                }
            );

        button.RegisterCallback<PointerLeaveEvent>(_ =>
            fill.style.width = new StyleLength(Length.Percent(0)));

        button.RegisterCallback<ClickEvent>(_ =>
        {
            AudioHandlerData.AudioManager.PlayRandomEffect(transform, LightHouse.Audio.AutoGenerated.EffectsAudioName.Effect_ButtonCliqued);
            callback.Invoke();
        });
    }

    private void Play()
    {
        Debug.Log("Play clicked");
        SceneManager.LoadSceneAsync(1, LoadSceneMode.Single);
        // Ex: SceneManager.LoadScene("GameScene");
    }

    private void Settings()
    {
        Debug.Log("Settings clicked");
        // Ex: Open settings panel
    }

    private void Extras()
    {
        Debug.Log("Extras clicked");
        // Ex: Open extras menu
    }

    private void Quit()
    {
        Debug.Log("Quit clicked");
        Application.Quit();
    }
}
