using UnityEngine;
using LightHouse.Audio.AutoGenerated;

namespace LightHouse.Audio
{
    [CreateAssetMenu(fileName = "Music_", menuName = "LightHouse/Audio/Music")]
    public class MusicAudio : AudioClipGroup
    {
        public MusicsAudioName Category;
    }
}
