/// <auto-generated/>
namespace LightHouse.Audio.AutoGenerated
{
    public enum DialogueAudioName
    {
        TUTORIAL_RopeAttach,
        TUTORIAL_BoatArrival,
        TUTORIAL_ElectricalPannel,
        TUTORIAL_ElectricalPannel_2,
        TUTORIAL_ElectricalPannel_3,
        TUTORIAL_ElectricalPannel_4,
        TUTORIAL_ElectricCurrent,
        TUTORIAL_ElectricCurrent_2,
        TUTORIAL_FindMainKey,
        TUTORIAL_FindMainKey_2,
        TUTORIAL_EnterLighthouse,
    }
}
