/// <auto-generated/>
namespace LightHouse.Audio.AutoGenerated
{
    public enum EffectsAudioName
    {
        FrontDoorClose,
        LockedDoor,
        FrontDoorOpen,
        DoorInteriorOpen,
        UnlockDoor,
        StartGenerator,
        InventoryItem_Pickup,
        InventoryItem_Throw,
    }
}
