/// <auto-generated/>
namespace LightHouse.Audio.AutoGenerated
{
    public enum EffectsAudioName
    {
        Effect_CloseFrontDoor,
        Effect_LockedDoor,
        Effect_OpenFrontDoor,
        Effect_OpenInteriorDoor,
        Effect_UnlockDoor,
        Effect_OffGenetrator,
        Effect_RunningGenerator,
        Effect_StartGenerator,
        Effect_Pickup,
        Effect_Throw,
        Effect_FlashlightOff,
        Effect_FlashlightOn,
        Effect_ButtonCliqued,
        Effect_ButtonHover,
    }
}
