using UnityEngine;
using LightHouse.Audio.AutoGenerated;

namespace LightHouse.Audio
{
    [CreateAssetMenu(fileName = "Ambiance_", menuName = "LightHouse/Audio/Ambiance")]
    public class AmbianceAudio : BaseAudio_SO
    {
        public AmbianceAudioName Category;

        private void OnValidate()
        {
            if (displayName != name)
            {
                displayName = AudioUtils.SanitizeName(name);
                if (System.Enum.TryParse<AmbianceAudioName>(displayName, out var parsed))
                {
                    Category = parsed;
                }
            }
        }
    }
}
