using UnityEngine;
using LightHouse.Audio.AutoGenerated;

namespace LightHouse.Audio
{
    [CreateAssetMenu(fileName = "Ambiance_", menuName = "LightHouse/Audio/Ambiance")]
    public class AmbianceAudio : AudioClipGroup
    {
        public AmbianceAudioName Category;
    }
}
