using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;

[CreateAssetMenu(fileName = "Ambiance_", menuName = "LightHouse/Audio/Ambiance")]
public class AmbianceAudio : AudioClipGroup
{
    public AmbianceAudioName Category;
}
