using UnityEngine;
using LightHouse.Audio.AutoGenerated;

namespace LightHouse.Audio
{
    [CreateAssetMenu(fileName = "Music_", menuName = "LightHouse/Audio/Music")]
    public class MusicAudio : BaseAudio_SO
    {
        public MusicsAudioName Category;

        private void OnValidate()
        {
            if (displayName != name)
            {
                displayName = AudioUtils.SanitizeName(name);
                if (System.Enum.TryParse<MusicsAudioName>(displayName, out var parsed))
                {
                    Category = parsed;
                }
            }
        }
    }
}
