using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using LightHouse.Audio.AutoGenerated;

[CreateAssetMenu(fileName = "Effect_", menuName = "LightHouse/Audio/Effect")]
public class EffectAudio : AudioClipGroup
{
    public EffectsAudioName Category;

}
