using UnityEngine;
using LightHouse.Audio.AutoGenerated;

namespace LightHouse.Audio
{
    [CreateAssetMenu(fileName = "Effect_", menuName = "LightHouse/Audio/Effect")]
    public class EffectAudio : AudioClipGroup
    {
        public EffectsAudioName Category;

        private void OnValidate()
        {
            if (displayName != name)
            {
                displayName = SanitizeName(name);
                if (System.Enum.TryParse<EffectsAudioName>(displayName, out var parsed))
                {
                    Category = parsed;
                }
            }
        }

    }

}
