using UnityEditor;
using UnityEngine;
using UnityEngine.Localization;
using UnityEditor.Localization;
using System.IO;
using System.Text;
using System.Linq;
using UnityEngine.Localization.Tables;

namespace LightHouse.CustomEditors
{
    public class LocalizationWindow : EditorWindow
    {
        private StringTableCollection stringTable;
        public string CustomAssetPath = "Assets/Localization/AutoGenerated";

        [MenuItem("Tools/Localization Window")]
        public static void ShowWindow()
        {
            GetWindow<LocalizationWindow>("Localization Window");
        }

        void OnGUI()
        {
            GUILayout.Label("Générer un ScriptableObject de LocalizedStrings", EditorStyles.boldLabel);

            stringTable = (StringTableCollection)EditorGUILayout.ObjectField("String Table", stringTable, typeof(StringTableCollection), false);
            CustomAssetPath = EditorGUILayout.TextField(CustomAssetPath);
            if (stringTable != null && GUILayout.Button("Générer le ScriptableObject"))
            {
                GenerateScriptableObjectFromTable(stringTable);
            }
        }

        void GenerateScriptableObjectFromTable(StringTableCollection table)
        {
            string className = $"LocalizedStringDatabase_{table.name}";
            string fileName = $"{className}.cs";
            string folderPath = Path.Combine(CustomAssetPath); // <- Utilise le chemin personnalisé
            string intendedScriptPath = Path.Combine(folderPath, fileName);

            // ➡️ Recherche dans tout le projet s'il existe déjà un fichier C#
            string existingScriptPath = AssetDatabase.FindAssets($"{className} t:script")
                .Select(guid => AssetDatabase.GUIDToAssetPath(guid))
                .FirstOrDefault(path => Path.GetFileName(path) == fileName);

            // ➡️ Si on trouve un fichier existant autre part
            if (!string.IsNullOrEmpty(existingScriptPath))
            {
                bool overwrite = EditorUtility.DisplayDialog(
                    "Fichier existant",
                    $"Un script {fileName} existe déjà ici :\n{existingScriptPath}\nVeux-tu l'écraser avec la nouvelle version ?",
                    "Écraser",
                    "Annuler");

                if (!overwrite)
                {
                    Debug.Log("⛔ Annulation de la génération du script par l'utilisateur.");
                    return;
                }

                intendedScriptPath = existingScriptPath; // Remplacer pour écraser l'ancien
            }
            else
            {
                // Dossier pas existant ? On le crée
                if (!Directory.Exists(folderPath))
                    Directory.CreateDirectory(folderPath);
            }

            // ➡️ Écriture du script
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// Auto-generated ScriptableObject for localization keys");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Localization;");
            sb.AppendLine();
            sb.AppendLine("namespace LightHouse.Localization");
            sb.AppendLine("{");
            sb.AppendLine($"\t[CreateAssetMenu(menuName = \"Localization/{className}\")]");
            sb.AppendLine($"\tpublic class {className} : ScriptableObject");
            sb.AppendLine("\t{");

            foreach (SharedTableData.SharedTableEntry entry in table.SharedData.Entries)
            {
                string key = entry.Key;
                sb.AppendLine($"\t\tpublic LocalizedString {SanitizeKey(key)};");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            File.WriteAllText(intendedScriptPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"✅ Script généré : {intendedScriptPath}");

            // ➡️ Créer/Maj l'asset après
            EditorApplication.delayCall += () =>
            {
                CreateAndPopulateInstance(className, table, Path.GetDirectoryName(intendedScriptPath));
            };
        }
        void CreateAndPopulateInstance(string className, StringTableCollection table, string folderPath)
        {
            var type = System.AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a => a.GetTypes())
                .FirstOrDefault(t => t.Name == className);

            if (type == null)
            {
                Debug.LogError($"Impossible de trouver le type {className} après génération.");
                return;
            }

            string assetPath = Path.Combine(folderPath, $"{className}.asset");
            ScriptableObject asset = AssetDatabase.LoadAssetAtPath(assetPath, type) as ScriptableObject;

            if (asset == null)
            {
                asset = ScriptableObject.CreateInstance(type);
                AssetDatabase.CreateAsset(asset, assetPath);
                Debug.Log($"✅ Nouvel asset créé : {assetPath}");
            }
            else
            {
                Debug.Log($"⚠️ Asset déjà existant, il sera mis à jour : {assetPath}");
            }

            foreach (SharedTableData.SharedTableEntry entry in table.SharedData.Entries)
            {
                string key = entry.Key;
                string fieldName = SanitizeKey(key);
                var field = type.GetField(fieldName);
                if (field != null && field.FieldType == typeof(LocalizedString))
                {
                    LocalizedString currentValue = field.GetValue(asset) as LocalizedString;

                    if (currentValue == null || currentValue.TableEntryReference != key || currentValue.TableReference != table.TableCollectionNameReference)
                    {
                        LocalizedString localizedString = new LocalizedString
                        {
                            TableReference = table.TableCollectionNameReference,
                            TableEntryReference = key
                        };
                        field.SetValue(asset, localizedString);
                    }
                }
            }

            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"✅ ScriptableObject mis à jour : {assetPath}");
        }



        string SanitizeKey(string key)
        {
            StringBuilder sb = new StringBuilder();
            foreach (char c in key)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            string result = sb.ToString();
            if (char.IsDigit(result[0])) result = "_" + result;

            return result;
        }
    }

}
