using UnityEditor;
using UnityEngine;
using UnityEngine.Localization;
using UnityEngine.Localization.Tables;
using UnityEditor.Localization;
using System.IO;
using System.Text;
using System.Linq;
using System;
using System.Reflection;

namespace LightHouse.CustomEditors
{
    public class LocalizationWindow : EditorWindow
    {
        private LocalizationTableCollection selectedTable;
        private Type selectedAssetType = typeof(Sprite); // Par défaut
        private string[] assetTypeOptions = new string[] { "Sprite", "AudioClip", "GameObject", "TextAsset" };
        private int selectedAssetTypeIndex = 0;

        public string CustomAssetPath = "Assets/Localization/AutoGenerated";

        [MenuItem("Tools/Localization Window")]
        public static void ShowWindow()
        {
            GetWindow<LocalizationWindow>("Localization Window");
        }

        void OnGUI()
        {
            GUILayout.Label("Générer un ScriptableObject de Localized Entries", EditorStyles.boldLabel);

            selectedTable = (LocalizationTableCollection)EditorGUILayout.ObjectField("Table (String ou Asset)", selectedTable, typeof(LocalizationTableCollection), false);

            CustomAssetPath = EditorGUILayout.TextField("Chemin du dossier", CustomAssetPath);

            if (selectedTable is AssetTableCollection)
            {
                GUILayout.Label("Type d'asset (pour LocalizedAsset<T>)");
                selectedAssetTypeIndex = EditorGUILayout.Popup(selectedAssetTypeIndex, assetTypeOptions);
                selectedAssetType = Type.GetType("UnityEngine." + assetTypeOptions[selectedAssetTypeIndex] + ", UnityEngine");
            }

            if (selectedTable != null && GUILayout.Button("Générer le ScriptableObject"))
            {
                GenerateScript(selectedTable);
            }
        }

        void GenerateScript(LocalizationTableCollection table)
        {
            string className = $"LocalizedDatabase_{table.name}";
            string fileName = $"{className}.cs";
            string folderPath = CustomAssetPath;
            string fullScriptPath = Path.Combine(folderPath, fileName);

            if (!Directory.Exists(folderPath))
                Directory.CreateDirectory(folderPath);

            var sharedEntries = table.SharedData.Entries;

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// Auto-generated ScriptableObject for localization keys");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Localization;");
            sb.AppendLine("using UnityEngine.Localization.Components;");
            sb.AppendLine();

            sb.AppendLine("namespace LightHouse.Localization");
            sb.AppendLine("{");
            sb.AppendLine($"\t[CreateAssetMenu(menuName = \"Localization/{className}\")]");
            sb.AppendLine($"\tpublic class {className} : ScriptableObject");
            sb.AppendLine("\t{");

            foreach (var entry in sharedEntries)
            {
                string sanitized = SanitizeKey(entry.Key);
                if (table is StringTableCollection)
                    sb.AppendLine($"\t\tpublic LocalizedString {sanitized};");
                else
                    sb.AppendLine($"\t\tpublic LocalizedAsset<{selectedAssetType.Name}> {sanitized};");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            File.WriteAllText(fullScriptPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"✅ Script généré : {fullScriptPath}");

            EditorApplication.delayCall += () =>
            {
                CreateAndPopulateSO(className, table, folderPath);
            };
        }

        void CreateAndPopulateSO(string className, LocalizationTableCollection table, string folderPath)
        {
            var type = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a => a.GetTypes())
                .FirstOrDefault(t => t.Name == className);

            if (type == null)
            {
                Debug.LogError($"❌ Type {className} introuvable après compilation.");
                return;
            }

            string assetPath = Path.Combine(folderPath, $"{className}.asset");
            ScriptableObject asset = AssetDatabase.LoadAssetAtPath(assetPath, type) as ScriptableObject;

            if (asset == null)
            {
                asset = ScriptableObject.CreateInstance(type);
                AssetDatabase.CreateAsset(asset, assetPath);
                Debug.Log($"✅ Asset créé : {assetPath}");
            }
            else
            {
                Debug.Log($"⚠️ Asset existant mis à jour : {assetPath}");
            }

            foreach (var entry in table.SharedData.Entries)
            {
                string key = entry.Key;
                string fieldName = SanitizeKey(key);
                var field = type.GetField(fieldName, BindingFlags.Public | BindingFlags.Instance);
                if (field == null) continue;

                if (table is StringTableCollection && field.FieldType == typeof(LocalizedString))
                {
                    var locString = new LocalizedString
                    {
                        TableReference = table.TableCollectionNameReference,
                        TableEntryReference = key
                    };
                    field.SetValue(asset, locString);
                }
                else if (table is AssetTableCollection && field.FieldType.IsGenericType &&
                         field.FieldType.GetGenericTypeDefinition() == typeof(LocalizedAsset<>))
                {
                    var localizedAsset = Activator.CreateInstance(field.FieldType) as LocalizedAssetBase;
                    localizedAsset.TableReference = table.TableCollectionNameReference;
                    localizedAsset.TableEntryReference = key;
                    field.SetValue(asset, localizedAsset);
                }
            }

            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        string SanitizeKey(string key)
        {
            var sb = new StringBuilder();
            foreach (char c in key)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }
    }
}
