using UnityEditor;
using UnityEngine;
using UnityEngine.Localization;
using UnityEditor.Localization;
using System.IO;
using System.Text;
using System.Linq;
using UnityEngine.Localization.Tables;

namespace LightHouse.CustomEditors
{
    public class LocalizationWindow : EditorWindow
    {
        private StringTableCollection stringTable;

        [MenuItem("Tools/Localization Window")]
        public static void ShowWindow()
        {
            GetWindow<LocalizationWindow>("Localization Window");
        }

        void OnGUI()
        {
            GUILayout.Label("Générer un ScriptableObject de LocalizedStrings", EditorStyles.boldLabel);

            stringTable = (StringTableCollection)EditorGUILayout.ObjectField("String Table", stringTable, typeof(StringTableCollection), false);

            if (stringTable != null && GUILayout.Button("Générer le ScriptableObject"))
            {
                GenerateScriptableObjectFromTable(stringTable);
            }
        }

        void GenerateScriptableObjectFromTable(StringTableCollection table)
        {
            string className = $"LocalizedStringDatabase_{table.name}";
            string folderPath = "Assets/Localization/AutoGenerated";
            string scriptPath = Path.Combine(folderPath, $"{className}.cs");

            if (!Directory.Exists(folderPath))
                Directory.CreateDirectory(folderPath);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// Auto-generated ScriptableObject for localization keys");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Localization;");
            sb.AppendLine();
            sb.AppendLine("namespace LightHouse.Localization");
            sb.AppendLine("{");
            sb.AppendLine($"\t[CreateAssetMenu(menuName = \"Localization/{className}\")]");
            sb.AppendLine($"\tpublic class {className} : ScriptableObject");
            sb.AppendLine("\t{");

            foreach (SharedTableData.SharedTableEntry entry in table.SharedData.Entries)
            {
                string key = entry.Key;
                sb.AppendLine($"\t\tpublic LocalizedString {SanitizeKey(key)};");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            File.WriteAllText(scriptPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"ScriptableObject class générée avec succès : {scriptPath}");

            // 2. Création de l’instance .asset après compilation
            EditorApplication.delayCall += () =>
            {
                CreateAndPopulateInstance(className, table);
            };
        }

        void CreateAndPopulateInstance(string className, StringTableCollection table)
        {
            var type = System.AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a => a.GetTypes())
                .FirstOrDefault(t => t.Name == className);

            if (type == null)
            {
                Debug.LogError($"Impossible de trouver le type {className} après génération.");
                return;
            }

            string assetPath = $"Assets/Localization/AutoGenerated/{className}.asset";
            ScriptableObject asset = AssetDatabase.LoadAssetAtPath(assetPath, type) as ScriptableObject;

            if (asset == null)
            {
                asset = ScriptableObject.CreateInstance(type);
                AssetDatabase.CreateAsset(asset, assetPath);
                Debug.Log($"Nouvel asset créé : {assetPath}");
            }
            else
            {
                Debug.Log($"L'asset existe déjà, il sera mis à jour : {assetPath}");
            }

            foreach (SharedTableData.SharedTableEntry entry in table.SharedData.Entries)
            {
                string key = entry.Key;
                string fieldName = SanitizeKey(key);
                System.Reflection.FieldInfo field = type.GetField(fieldName);
                if (field != null && field.FieldType == typeof(LocalizedString))
                {
                    LocalizedString currentValue = field.GetValue(asset) as LocalizedString;

                    // Remplir si null ou entrée différente
                    if (currentValue == null || currentValue.TableEntryReference != key || currentValue.TableReference != table.TableCollectionNameReference)
                    {
                        LocalizedString localizedString = new LocalizedString
                        {
                            TableReference = table.TableCollectionNameReference,
                            TableEntryReference = key
                        };
                        field.SetValue(asset, localizedString);
                    }
                }
            }

            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"ScriptableObject mis à jour : {assetPath}");
        }


        string SanitizeKey(string key)
        {
            StringBuilder sb = new StringBuilder();
            foreach (char c in key)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            string result = sb.ToString();
            if (char.IsDigit(result[0])) result = "_" + result;

            return result;
        }
    }

}
