using LightHouse.Audio;

namespace LightHouse.Inventory
{
    public class InventoryPickupHandler
    {
        #region PICKUP 
        public bool PickupItem(short slotIndex, IInventoryItem item)
        {
            if (item == null) return false;
            ItemSlot targetSlot = null;

            if (SlotManager.IsSlotInvalidOrOccupied(slotIndex))
            {
                SlotManager.FindFirstEmptySlot(out targetSlot);
            }
            else
            {
                if(!SlotManager.CurrentSelectedSlot.SlotDatas.HasItem)
                    targetSlot = SlotManager.Slots[slotIndex];
            }

            if (item is IInventoryStackable stackable)
            {
                if (SlotManager.TryFindStackableSlot(item.GlobalItemID, out ItemSlot existingSlot))
                {
                    if (existingSlot.SlotDatas.TotalItemsInSlots < existingSlot.SlotDatas.MaxStack)
                        targetSlot = existingSlot;
                }

                if (targetSlot != null && targetSlot.SlotDatas.TotalItemsInSlots == 0)
                    targetSlot.SlotDatas.MaxStack = stackable.MaxStack;
            }

            if (targetSlot == null) return false; //inventory full even for the stackable ones

            PoolManager.Add(item);
            item.IsItemInInventory = true;
            if(AudioHandlerData.AudioManager != null)
                AudioHandlerData.AudioManager.PlayRandomEffect(item.GetGameObject().transform.position, Audio.AutoGenerated.EffectsAudioName.Effect_Pickup);
            targetSlot.AddItemDatasToSlot(item);
            targetSlot.SubscribeToIInventoryItem(item);
            if(item is IInventoryItemUsable usable) targetSlot.SubscribeToIInventoryUsable(usable);
            if (item is IInventoryItemCallback callback) callback.OnItemAddedToInventory();
            return true;
        }
        #endregion
    }

}
